package com.diagrammingtool.app.model;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class UserRegistrationTest {

    @Test
    public void testConstructorAndGetters() {
        // Create a UserRegistration object using the constructor
        UserRegistration user = new UserRegistration("John", "Doe", "john@example.com", "Password123!");
        assertNull(user.getUserId()); // Id should be null since it's generated by the database
        assertEquals("John", user.getFirstName());
        assertEquals("Doe", user.getLastName());
        assertEquals("john@example.com", user.getUserEmail());
        assertEquals("Password123!", user.getPassword());
    }

    @Test
    public void testSetters() {
        UserRegistration user = new UserRegistration();
       user.setFirstName("Jane");
        user.setLastName("Doe");
        user.setUserEmail("jane@example.com");
        user.setPassword("Password123!");

        assertNull(user.getUserId());
        assertEquals("Jane", user.getFirstName());
        assertEquals("Doe", user.getLastName());
        assertEquals("jane@example.com", user.getUserEmail());
        assertEquals("Password123!", user.getPassword());
    }

   
}
