package com.diagrammingtool.app.model;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class UserRegistrationTest {

    @Test
    public void testConstructorAndGetters() {
        // Create a UserRegistration object using the constructor
        UserRegistration user = new UserRegistration("John", "Doe", "john@example.com", "Password123!");

        // Verify that the constructor sets the fields correctly
        assertNull(user.getUserId()); // Id should be null since it's generated by the database
        assertEquals("John", user.getFirstName());
        assertEquals("Doe", user.getLastName());
        assertEquals("john@example.com", user.getUserEmail());
        assertEquals("Password123!", user.getPassword());
    }

    @Test
    public void testSetters() {
        // Create a UserRegistration object
        UserRegistration user = new UserRegistration();

        // Set the fields using setters
        user.setFirstName("Jane");
        user.setLastName("Doe");
        user.setUserEmail("jane@example.com");
        user.setPassword("Password123!");

        // Verify that the setters set the fields correctly
        assertNull(user.getUserId()); // Id should remain null
        assertEquals("Jane", user.getFirstName());
        assertEquals("Doe", user.getLastName());
        assertEquals("jane@example.com", user.getUserEmail());
        assertEquals("Password123!", user.getPassword());
    }

   
}
